AirWaysClient/Models/TravelRegistration.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AirWaysClient.Models
{
    public class TravelRegistration
    {
        public int TravelRegistrationID { get; set; }
        public int TravelID { get; set; }
        public int CustomerID { get; set; }
        public decimal TRavelPrice { get; set; }
        public System.DateTime TravelDate { get; set; }
        public System.DateTime TravelRegistrationDate { get; set; }
        public int TravelSeatsBooked { get; set; }

    }
}

AirWaysClient/Models/TravelRegistrationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AirWaysClient.Models
{
    public class TravelRegistrationViewModel
    {
        public int TravelRegistrationID { get; set; }
        public int TravelID { get; set; }
        public int CustomerID { get; set; }
        public decimal TRavelPrice { get; set; }
        public System.DateTime TravelDate { get; set; }
        public System.DateTime TravelRegistrationDate { get; set; }
        public int TravelSeatsBooked { get; set; }
        public int TravelID1 { get; set; }
        public int TravelAvailableSeats { get; set; }
        public int TravelTarget { get; set; }
        public int TravelSource { get; set; }
        public decimal TravelPrice1 { get; set; }
        public DateTime TravelDate1 { get; set; }
        public int TravelSeatCapacity { get; set; }
        public int CustomerID1 { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAdress { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerIDCard { get; set; }
        public string Destino { get; set; }
        public string Origen { get; set; }
    }
}

AirWaysClient/Controllers/TravelRegistrationsController.cs
using AirWaysClient.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace AirWaysClient.Controllers
{
    public class TravelRegistrationsController : Controller
    {
        /// <summary>
        /// Cliente Http para hacer los request a la Api.
        /// Este objeto lo creo de forma estatica para poder reutilizarlo en toda la aplicacion sin tener que
        /// instanciarlo nuevamente. asi se evitan errores de conexiones a la api.
        /// </summary>
        private static HttpClient client = HttpClientTaker.GetClient();

        /// <summary>
        /// Vuelos Registrados, es una cache temporal para evitar demasiados llamados a la api.
        /// </summary>
        private static List<TravelViewModel> Travels = new List<TravelViewModel>();
        /// <summary>
        /// Clientes registrados, es una cache temporal para evitar demasiados llamados a la api.
        /// </summary>
        private static List<Customer> Customers = new List<Customer>();


        // GET: TravelRegistrations
        public ActionResult Index(string mensajePositivo = null, string mensajeNegativo = null)
        {
            //Setear las propiedades de los mensajes que se van a mostrar en el fromnt.
            if (mensajePositivo != null)
            {
                ViewBag.mensajePositivo = mensajePositivo;
            }
            if (mensajeNegativo != null)
            {
                ViewBag.mensajeNegativo = mensajeNegativo;
            }

            List<TravelRegistrationViewModel> destinos = new List<TravelRegistrationViewModel>();
            var resultado = client.GetAsync("api/TravelRegistrations").Result;
            if (resultado.IsSuccessStatusCode)
            {
                destinos = resultado.Content.ReadAsAsync<List<TravelRegistrationViewModel>>().Result;
            }
            else
            {
                ViewBag.mensajeNegativo = resultado.ReasonPhrase;
            }
            return View(destinos);
        }

        [HttpGet]
        public ActionResult Create()
        {
            //busco la lista de clientes y l almaceno de forma temporal para hacer el viewbag yendo a la api la menor cantidas de veces posible.
            //lo mismo hago con los vuelos disponibles
            Customers = client.GetAsync("api/customers").Result.Content.ReadAsAsync<List<Customer>>().Result;
            ViewBag.customers = new SelectList(Customers, "CustomerID", "CustomerName");

            Travels = client.GetAsync("api/travels").Result.Content.ReadAsAsync<List<TravelViewModel>>().Result;

            ViewBag.travels = new SelectList(Travels, "TravelID", "InfoTravel");
            TravelRegistration registration = new TravelRegistration();
            return View(registration);
        }

        public ActionResult Create(TravelRegistration travel)
        {
            ViewBag.customers = new SelectList(Customers, "CustomerID", "CustomerName");
            ViewBag.travels = new SelectList(Travels, "TravelID", "InfoTravel");
            if (travel.TravelSeatsBooked <= 0)
            {
                ViewBag.mensajeNegativo = "Seleccione la cantidad de asientos que desea reservar";
                return View(travel);
            }
            travel.TravelDate = Travels.Where(t => t.TravelID == travel.TravelID).Select(t => t.TravelDate).FirstOrDefault();
            travel.TRavelPrice = Travels.Where(t => t.TravelID == travel.TravelID).Select(t => t.TravelPrice).FirstOrDefault();
            travel.TravelRegistrationDate = DateTime.Now;
            var resultado = client.PostAsJsonAsync("api/TravelRegistrations", travel).Result;
            if (resultado.IsSuccessStatusCode)
            {
                return RedirectToAction("Index", new { mensajePositivo = "Informacion guardada de forma Exitosa" });
            }
            else
            {
                ViewBag.mensajeNegativo = resultado.ReasonPhrase;
                return View(travel);
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            //busco la lista de clientes y l almaceno de forma temporal para hacer el viewbag yendo a la api la menor cantidas de veces posible.
            //lo mismo hago con los vuelos disponibles
            Customers = client.GetAsync("api/customers").Result.Content.ReadAsAsync<List<Customer>>().Result;
            ViewBag.customers = new SelectList(Customers, "CustomerID", "CustomerName");

            Travels = client.GetAsync("api/travels").Result.Content.ReadAsAsync<List<TravelViewModel>>().Result;
            ViewBag.travels = new SelectList(Travels, "TravelID", "InfoTravel");

            var resultado = client.GetAsync("api/TravelRegistrations/" + id).Result;
            if (resultado.IsSuccessStatusCode)
            {
                var registro = resultado.Content.ReadAsAsync<TravelRegistrationViewModel>().Result;
                //a partir del vewmodel de travelRegistration armo el modelo que necesita la vista.
                TravelRegistration travel = new TravelRegistration
                {
                    CustomerID = registro.CustomerID,
                    TravelID = registro.TravelID,
                    TravelSeatsBooked = registro.TravelSeatsBooked,
                    TravelRegistrationDate = registro.TravelRegistrationDate,
                    TravelRegistrationID = registro.TravelRegistrationID
                };
                return View(travel);
            }
            else
            {
                return RedirectToAction("Index", new { mensajeNegativo = resultado.ReasonPhrase });
            }
        }

        [HttpPost]
        public ActionResult Edit(TravelRegistration travel)
        {
            ViewBag.customers = new SelectList(Customers, "CustomerID", "CustomerName");
            ViewBag.travels = new SelectList(Travels, "TravelID", "InfoTravel");
            if (travel.TravelSeatsBooked <= 0)
            {
                ViewBag.mensajeNegativo = "Seleccione la cantidad de asientos que desea reservar";
                return View(travel);
            }
            travel.TravelDate = Travels.Where(t => t.TravelID == travel.TravelID).Select(t => t.TravelDate).FirstOrDefault();
            travel.TRavelPrice = Travels.Where(t => t.TravelID == travel.TravelID).Select(t => t.TravelPrice).FirstOrDefault();
            var resultado = client.PutAsJsonAsync("api/TravelRegistrations/" + travel.TravelRegistrationID, travel).Result;
            if (resultado.IsSuccessStatusCode)
            {
                return RedirectToAction("Index", new { mensajePositivo = "Informacion guardada de forma Exitosa" });
            }
            else
            {
                ViewBag.mensajeNegativo = resultado.ReasonPhrase;
                return View(travel);
            }
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var resultado = client.GetAsync("api/TravelRegistrations/" + id).Result;
            if (resultado.IsSuccessStatusCode)
            {
                var registro = resultado.Content.ReadAsAsync<TravelRegistrationViewModel>().Result;
                return View(registro);
            }
            else
            {
                return RedirectToAction("Index", new { mensajeNegativo = resultado.ReasonPhrase });
            }
        }

        [HttpPost]
        public ActionResult Delete(TravelRegistrationViewModel travel)
        {
            var resultado = client.DeleteAsync("api/TravelRegistrations/" + travel.TravelRegistrationID).Result;
            if (resultado.IsSuccessStatusCode)
            {
                return RedirectToAction("Index", new { mensajePositivo = "Informacion guardada de manera exitosa" });
            }
            else
            {
                return RedirectToAction("Index", new { mensajeNegativo = resultado.ReasonPhrase });
            }
        }

        /// <summary>
        /// metodo para buscar la cantidad de asientos disponibles una vez que el usuario indicó en el front que vuelo quiere reservar
        /// </summary>
        /// <param name="travelid">el vuelo del que quiero conocer su disponibilidad</param>
        /// <returns></returns>
        public JsonResult GetSeatsRemaining(int travelid)
        {
            int seats = Travels.FirstOrDefault(t => t.TravelID == travelid).TravelAvailableSeats;
            return Json(seats, JsonRequestBehavior.AllowGet);
        }
    }
}

AirWaysClient/Views/TravelRegistrations/Create.cshtml
@model AirWaysClient.Models.TravelRegistration

<h2>Reservacion de vuelos</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Nueva reservacion de Vuelo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TravelID, "Vuelo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TravelID", ViewBag.travels as SelectList, "Seleccione", new { @class = "form-control", @id = "TravelID" })
                @Html.ValidationMessageFor(model => model.TravelID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CustomerID", ViewBag.customers as SelectList, "Seleccione", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CustomerID, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TravelSeatsBooked, "Numero de Asientos", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TravelSeatsBooked, new { htmlAttributes = new { @class = "form-control", @type="number", @min="1", @max="1", @id= "TravelSeatsBooked" } })
                <label class="label label-success hidden" id="asientos">Asientos Disponibles</label>
                @Html.ValidationMessageFor(model => model.TravelSeatsBooked, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-danger" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @if (ViewBag.mensajeNegativo != null)
    {
        <script type="text/javascript">
            $(document).ready(function () {
                swal("Error al guardar los datos", "@ViewBag.mensajeNegativo", "error");
            })
        </script>
    }

    @if (ViewBag.mensajePositivo != null)
    {
        <script type="text/javascript">
            $(document).ready(function () {
                swal("Exito", "@ViewBag.mensajePositivo", "success");
            })
        </script>
    }

    
    <script type="text/javascript">
        //Solicitar la cantidad de asientos disponibles para un vuelo seleccionado
        $("#TravelID").change(function (e) {
            var seleccion = $("#TravelID").val();
            if (seleccion != "") {
                $.ajax({
                    url: '@Url.Action("GetSeatsRemaining")',
                    dataType: 'json',
                    data: { travelid : seleccion },
                    success: function (seats) {
                        document.getElementById("TravelSeatsBooked").setAttribute("max", seats);
                        var text = "Asientos disponibles: " + seats;
                        $("#asientos").text(text);
                        $("#asientos").removeClass("hidden");
                    },
                    error: function (xh) {
                        console.log(xh);
                    }
                })
            } else {
                $("#asientos").text = "sientos disponibles:";
                $("#asientos").addClass("hidden");
            }
        })

    </script>
    }

AirWaysClient/Views/TravelRegistrations/Delete.cshtml
@model AirWaysClient.Models.TravelRegistrationViewModel

<h2>Reservaciones</h2>

<div>
    <h4>Eliminar Reservacion</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.Label("cliente")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerName)
        </dd>

        <dt>
            @Html.Label("Nº identificacion")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerIDCard)
        </dd>

        <dt>
            @Html.Label("Destino")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Destino)
        </dd>

        <dt>
            @Html.Label("Origen")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Origen)
        </dd>
        <dt>
            @Html.Label("Asientos Reservados")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TravelSeatsBooked)
        </dd>

        <dt>
            @Html.Label("Precio")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TRavelPrice)
        </dd>

        <dt>
            @Html.Label("Fecha Salida")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TravelDate)
        </dd>

        <dt>
            @Html.Label("Fecha registro")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TravelRegistrationDate)
        </dd>





    </dl>

    @using (Html.BeginForm("Delete", "TravelRegistrations", FormMethod.Post, new { @id = "FormDelete" }))
    {
        @Html.HiddenFor(model => model.TravelRegistrationID)

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" id="delete" class="btn btn-default" />
            @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-danger" })
        </div>
    }
</div>
@section scripts{
    <script type="text/javascript">
        $('#delete').click(function (e) {
            e.preventDefault();
            swal({
                title: "Eliminar Registro?",
                text: "El registro se eliminará de forma permanente",
                type: "warning",
                showCancelButton: true,
                confirmButtonClass: "btn-danger",
                confirmButtonText: "Borrar",
                cancelButtonText: "Cancelar",
                closeOnConfirm: false,
                closeOnCancel: false
            },
                function (isConfirm) {
                    if (isConfirm) {
                        $("#FormDelete").submit();
                    } else {
                        swal("Cancelado", "No de borrará el registro", "error");
                    }
                });

        })

    </script>
}

AirWaysClient/Views/TravelRegistrations/Edit.cshtml
@model AirWaysClient.Models.TravelRegistration

<h2>Reservacion de vuelos</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Editar reservacion de Vuelo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TravelID, "Vuelo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TravelID", ViewBag.travels as SelectList, "Seleccione", new { @class = "form-control", @id = "TravelID" })
                @Html.ValidationMessageFor(model => model.TravelID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CustomerID", ViewBag.customers as SelectList, "Seleccione", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CustomerID, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TravelSeatsBooked, "Numero de Asientos", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TravelSeatsBooked, new { htmlAttributes = new { @class = "form-control", @type = "number", @min = "1", @max = "1", @id = "TravelSeatsBooked" } })
                <label class="label label-success hidden" id="asientos">Asientos Disponibles</label>
                @Html.ValidationMessageFor(model => model.TravelSeatsBooked, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.HiddenFor(model => model.TravelRegistrationDate)
        @Html.HiddenFor(model => model.TravelRegistrationID)
        @Html.HiddenFor(model => model.TravelID)
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-danger" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @if (ViewBag.mensajeNegativo != null)
    {
        <script type="text/javascript">
            $(document).ready(function () {
                swal("Error al guardar los datos", "@ViewBag.mensajeNegativo", "error");
            })
        </script>
    }

    @if (ViewBag.mensajePositivo != null)
    {
        <script type="text/javascript">
            $(document).ready(function () {
                swal("Exito", "@ViewBag.mensajePositivo", "success");
            })
        </script>
    }

    <script type="text/javascript">
        $(document).ready(function () {
            var seleccion = $("#TravelID").val();
            if (seleccion != "") {
                $.ajax({
                    url: '@Url.Action("GetSeatsRemaining")',
                    dataType: 'json',
                    data: { travelid : seleccion },
                    success: function (seats) {
                        document.getElementById("TravelSeatsBooked").setAttribute("max", seats);
                        var text = "Asientos disponibles: " + seats;
                        $("#asientos").text(text);
                        $("#asientos").removeClass("hidden");
                    },
                    error: function (xh) {
                        console.log(xh);
                    }
                })
            } else {
                $("#asientos").text = "sientos disponibles:";
                $("#asientos").addClass("hidden");
            }
        })
    </script>

    <script type="text/javascript">
        //Solicitar la cantidad de asientos disponibles para un vuelo seleccionado
        $("#TravelID").change(function (e) {
            var seleccion = $("#TravelID").val();
            if (seleccion != "") {
                $.ajax({
                    url: '@Url.Action("GetSeatsRemaining")',
                    dataType: 'json',
                    data: { travelid : seleccion },
                    success: function (seats) {
                        document.getElementById("TravelSeatsBooked").setAttribute("max", seats);
                        var text = "Asientos disponibles: " + seats;
                        $("#asientos").text(text);
                        $("#asientos").removeClass("hidden");
                    },
                    error: function (xh) {
                        console.log(xh);
                    }
                })
            } else {
                $("#asientos").text = "sientos disponibles:";
                $("#asientos").addClass("hidden");
            }
        })

    </script>
}

AirWaysClient/Views/TravelRegistrations/Index.cshtml
@model IEnumerable<AirWaysClient.Models.TravelRegistrationViewModel>

<h2>Reservaciones de Vuelos</h2>

<p>
    @Html.ActionLink("Crear nueva reservacion", "Create", null, new { @class = "btn btn-success" })
</p>

<table class="table table-responsive table-striped">
    <thead>
        <tr>
            <th>
                @Html.Label("Cliente")
            </th>
            <th>
                @Html.Label("Nº identificacion")
            </th>
            <th>
                @Html.Label("Origen")
            </th>
            <th>
                @Html.Label("Destino")
            </th>
            <th>
                @Html.Label("Precio")
            </th>
            <th>
                @Html.Label("Fecha salida")
            </th>
            <th>
                @Html.Label("Nº Asientos")
            </th>
            <th>
                @Html.Label("Fecha registro")
            </th>
            <th>
                @Html.Label("Acciones")
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CustomerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CustomerIDCard)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Origen)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Destino)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TRavelPrice)
                </td>
                <td>
                    @if (item.TravelDate > DateTime.Now)
                    {
                        @Html.Label(item.TravelDate.ToString(), new { @class = "label label-success" })
                    }
                    else
                    {
                        @Html.Label(item.TravelDate.ToString(), new { @class = "label label-danger" })
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TravelSeatsBooked)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TravelRegistrationDate)
                </td>
                <td>
                    @if (item.TravelDate > DateTime.Now)
                    {
                        @Html.ActionLink("Editar", "Edit", new { id = item.TravelRegistrationID }, new { @class = "btn btn-info btn-xs" })
                        @Html.ActionLink("Eliminar", "Delete", new {id = item.TravelRegistrationID }, new { @class = "btn btn-warning btn-xs" })
                    }
                    else
                    {
                        @Html.Label("-Expirado-", new {@class="label label-danger" })
                    }
                </td>
            </tr>
        }
    </tbody>
</table>


@section scripts{
    @if (ViewBag.mensajeNegativo != null)
    {
        <script type="text/javascript">
            $(document).ready(function () {
                swal("Error al leer los datos", "@ViewBag.mensajeNegativo", "error");
            })
        </script>
    }

    @if (ViewBag.mensajePositivo != null)
    {
        <script type="text/javascript">
            $(document).ready(function () {
                swal("Exito", "@ViewBag.mensajePositivo", "success");
            })
        </script>
    }
}