AirWaysClient/Models/Destination.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AirWaysClient.Models
{
    public class Destination
    {
        public int DestinationID { get; set; }
        public string DestinationCode { get; set; }
        public string DestinationName { get; set; }
    }
}

AirWaysClient/Controllers/DestinationsController.cs
using AirWaysClient.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace AirWaysClient.Controllers
{
    public class DestinationsController : Controller
    {
        /// <summary>
        /// Cliente Http para hacer los request a la Api.
        /// Este objeto lo creo de forma estatica para poder reutilizarlo en toda la aplicacion sin tener que
        /// instanciarlo nuevamente. asi se evitan errores de conexiones a la api.
        /// </summary>
        private static HttpClient client = HttpClientTaker.GetClient();

        // GET: Destinations
        public ActionResult Index(string mensajePositivo = null, string mensajeNegativo = null)
        {
            //Setear las propiedades de los mensajes que se van a mostrar en el fromnt.
            if (mensajePositivo != null)
            {
                ViewBag.mensajePositivo = mensajePositivo;
            }
            if (mensajeNegativo != null)
            {
                ViewBag.mensajeNegativo = mensajeNegativo;
            }

            List<Destination> destinos = new List<Destination>();
            var resultado = client.GetAsync("api/destinations").Result;
            if (resultado.IsSuccessStatusCode)
            {
                destinos = resultado.Content.ReadAsAsync<List<Destination>>().Result;
            }
            else
            {
                ViewBag.mensajeNegativo = resultado.ReasonPhrase;
            }
            return View(destinos);
        }

        [HttpGet]
        public ActionResult Create()
        {
            Destination destination = new Destination();
            return View(destination);
        }

        [HttpPost]
        public ActionResult Create(Destination model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.mensajeNegativo = "El modelo no es valido, Revise los datos";
                return View(model);
            }

            if (string.IsNullOrEmpty(model.DestinationCode) || string.IsNullOrEmpty(model.DestinationName))
            {
                ViewBag.mensajeNegativo = "Debe indicar un codigo y un nombre para el nuevo destino..";
                return View(model);
            }

            var resultado = client.PostAsJsonAsync("api/destinations", model).Result;
            if (resultado.IsSuccessStatusCode)
            {
                return RedirectToAction("Index", new { mensajePositivo = "Informacion guardada de forma Exitosa" });
            }
            else
            {
                ViewBag.mensajeNegativo = resultado.ReasonPhrase;
                return View(model);
            }
        }

        [HttpGet]
        public ActionResult Update(int id)
        {
            var resultado = client.GetAsync("api/destinations/" + id).Result;
            if (resultado.IsSuccessStatusCode)
            {
                var destino = resultado.Content.ReadAsAsync<Destination>().Result;
                return View(destino);
            }
            else
            {
                return RedirectToAction("Index", new { mensajeNegativo = resultado.ReasonPhrase });
            }
        }

        /// <summary>
        /// Metodo para hacer Update de un destino.
        /// el metodo redirige al index con una mensaje positivo o negativo dependiendo del resultado de la operacion en la api
        /// </summary>
        /// <param name="destination">el destino que se desea modificar</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Update(Destination destination)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.mensajeNegativo = "El modelo de datos que introdjo no es valido";
                return View(destination);
            }
            var resultado = client.PutAsJsonAsync("api/destinations/" + destination.DestinationID, destination).Result;
            if (resultado.IsSuccessStatusCode)
            {
                //var destino = resultado.Content.ReadAsAsync<Destination>().Result;
                return RedirectToAction("Index", new { mensajePositivo = "Informacion guardada de manera exitosa" });
            }
            else
            {
                return RedirectToAction("Index", new { mensajeNegativo = resultado.ReasonPhrase });
            }
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var resultado = client.GetAsync("api/destinations/" + id).Result;
            if (resultado.IsSuccessStatusCode)
            {
                var destino = resultado.Content.ReadAsAsync<Destination>().Result;
                return View(destino);
            }
            else
            {
                return RedirectToAction("Index", new { mensajeNegativo = resultado.ReasonPhrase });
            }
        }

        [HttpPost]
        public ActionResult Delete(Destination destination)
        {
            var resultado = client.DeleteAsync("api/destinations/" + destination.DestinationID).Result;
            if (resultado.IsSuccessStatusCode)
            {
                //var destino = resultado.Content.ReadAsAsync<Destination>().Result;
                return RedirectToAction("Index", new { mensajePositivo = "Informacion guardada de manera exitosa" });
            }
            else
            {
                return RedirectToAction("Index", new { mensajeNegativo = resultado.ReasonPhrase });
            }
        }
    }
}

AirWaysClient/Views/Destinations/Create.cshtml
@model AirWaysClient.Models.Destination

@{
    ViewBag.Title = "Create";
}

<h2>Destinos</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Nuevo destino</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DestinationCode, "Codigo Destino",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DestinationCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DestinationCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DestinationName, "Nombre Destino", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DestinationName,new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DestinationName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-danger"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    @if (ViewBag.mensajeNegativo != null)
    {
        <script type="text/javascript">
            $(document).ready(function () {
                swal("Error al guardar los datos", "@ViewBag.mensajeNegativo", "error");
            })
        </script>
    }

}

AirWaysClient/Views/Destinations/Delete.cshtml
@model AirWaysClient.Models.Destination

<h2>Destinos</h2>

<div>
    <h4>Eliminar Destino</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.Label("Codigo del Destino")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DestinationCode)
        </dd>

        <dt>
            @Html.Label("nombre del Destino")

        </dt>

        <dd>
            @Html.DisplayFor(model => model.DestinationName)
        </dd>

    </dl>

    @using (Html.BeginForm("Delete", "Destinations", FormMethod.Post, new { @id = "FormDelete" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.HiddenFor(m => Model.DestinationCode)
            @Html.HiddenFor(m => Model.DestinationID)
            @Html.HiddenFor(m => Model.DestinationName)
            <input type="submit" value="Eliminar" id="delete" class="btn btn-default" /> 
            @Html.ActionLink("Volver", "Index", null, new { @class="btn btn-danger"})
        </div>
    }
</div>

@section scripts{
    <script type="text/javascript">
        $('#delete').click(function (e) {
            e.preventDefault();
            swal({
                title: "Eliminar Registro?",
                text: "El registro se eliminará de forma permanente",
                type: "warning",
                showCancelButton: true,
                confirmButtonClass: "btn-danger",
                confirmButtonText: "Borrar",
                cancelButtonText: "Cancelar",
                closeOnConfirm: false,
                closeOnCancel: false
            },
                function (isConfirm) {
                    if (isConfirm) {
                        $("#FormDelete").submit();
                    } else {
                        swal("Cancelado", "No de borrará el registro", "error");
                    }
                });

        })

    </script>
}

AirWaysClient/Views/Destinations/Index.cshtml
@model IEnumerable<AirWaysClient.Models.Destination>

<h2>Destinos Registrados</h2>

<p>
    @Html.ActionLink("Crear nuevo destino", "Create", null, new { @class = "btn btn-success" })
</p>
<br />
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.Label("Codigo Destino")
            </th>
            <th>
                @Html.Label("Nombre Destino")
            </th>
            <th>
                @Html.Label("Acciones")
            </th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DestinationCode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DestinationName)
                </td>
                <td>
                    @Html.ActionLink("Editat", "Update", new { id = item.DestinationID }, new { @class = "btn btn-info" })
                    @Html.ActionLink("Eliminar", "Delete", new { id = item.DestinationID }, new { @class = "btn btn-warning" })
                </td>
            </tr>
        }
    </tbody>


</table>

@section scripts{
    @if (ViewBag.mensajeNegativo != null)
    {
        <script type="text/javascript">
            $(document).ready(function () {
                swal("Error al leer los datos", "@ViewBag.mensajeNegativo", "error");
            })
        </script>
    }

    @if (ViewBag.mensajePositivo != null)
    {
        <script type="text/javascript">
            $(document).ready(function () {
                swal("Exito", "@ViewBag.mensajePositivo", "success");
            })
        </script>
    }
}

AirWaysClient/Views/Destinations/Update.cshtml
@model AirWaysClient.Models.Destination

@{
    ViewBag.Title = "Update";
}

<h2>Actualizar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Actualizar Destino</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DestinationID)

        <div class="form-group">
            @Html.LabelFor(model => model.DestinationCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DestinationCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DestinationCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DestinationName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DestinationName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DestinationName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index",null, new { @class = "btn btn-danger"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    @if (ViewBag.mensajeNegativo != null)
    {
        <script type="text/javascript">
            $(document).ready(function () {
                swal("Error al guardar los datos", "@ViewBag.mensajeNegativo", "error");
            })
        </script>
    }

}