AirWaysClient/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AirWaysClient.Models
{
    public class Customer
    {
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAdress { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerIDCard { get; set; }
    }
}

AirWaysClient/Controllers/CustomersController.cs
using AirWaysClient.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace AirWaysClient.Controllers
{
    public class CustomersController : Controller
    {
        /// <summary>
        /// Cliente Http para hacer los request a la Api.
        /// Este objeto lo creo de forma estatica para poder reutilizarlo en toda la aplicacion sin tener que
        /// instanciarlo nuevamente. asi se evitan errores de conexiones a la api.
        /// </summary>
        private static HttpClient client = HttpClientTaker.GetClient();

        // GET: Customers
        public ActionResult Index(string mensajePositivo = null, string mensajeNegativo = null)
        {
            //Setear las propiedades de los mensajes que se van a mostrar en el fromnt.
            if (mensajePositivo != null)
            {
                ViewBag.mensajePositivo = mensajePositivo;
            }
            if (mensajeNegativo != null)
            {
                ViewBag.mensajeNegativo = mensajeNegativo;
            }

            List<Customer> customers = new List<Customer>();
            client = HttpClientTaker.GetTokenFromCookieAndSetToHttpClient(client);
            var resultado = client.GetAsync("api/customers").Result;
            if (resultado.IsSuccessStatusCode)
            {
                customers = resultado.Content.ReadAsAsync<List<Customer>>().Result;
            }
            else
            {
                ViewBag.mensajeNegativo = resultado.ReasonPhrase;
            }
            return View(customers);
        }

        [HttpGet]
        public ActionResult Create()
        {
            Customer c = new Customer();
            return View(c);
        }

        [HttpPost]
        public ActionResult Create(Customer model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.mensajeNegativo = "El modelo no es valido, Revise los datos";
                return View(model);
            }

            if (string.IsNullOrEmpty(model.CustomerAdress) || string.IsNullOrEmpty(model.CustomerIDCard) || string.IsNullOrEmpty(model.CustomerName) || string.IsNullOrEmpty(model.CustomerPhone))
            {
                ViewBag.mensajeNegativo = "Debe llenar todos los campos del formulario";
                return View(model);
            }

            var resultado = client.PostAsJsonAsync("api/customers", model).Result;
            if (resultado.IsSuccessStatusCode)
            {
                return RedirectToAction("Index", new { mensajePositivo = "Informacion guardada de forma Exitosa" });
            }
            else
            {
                ViewBag.mensajeNegativo = resultado.ReasonPhrase;
                return View(model);
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var resultado = client.GetAsync("api/customers/" + id).Result;
            if (resultado.IsSuccessStatusCode)
            {
                var cutomer = resultado.Content.ReadAsAsync<Customer>().Result;
                return View(cutomer);
            }
            else
            {
                return RedirectToAction("Index", new { mensajeNegativo = resultado.ReasonPhrase });
            }
        }

        /// <summary>
        /// Metodo para hacer Update de un customer.
        /// el metodo redirige al index con una mensaje positivo o negativo dependiendo del resultado de la operacion en la api
        /// </summary>
        /// <param name="customer">el customer que se desea modificar</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Edit(Customer customer)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.mensajeNegativo = "El modelo de datos que introdjo no es valido";
                return View(customer);
            }
            var resultado = client.PutAsJsonAsync("api/customers/" + customer.CustomerID, customer).Result;
            if (resultado.IsSuccessStatusCode)
            {
                return RedirectToAction("Index", new { mensajePositivo = "Informacion guardada de manera exitosa" });
            }
            else
            {
                return RedirectToAction("Index", new { mensajeNegativo = resultado.ReasonPhrase });
            }
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var resultado = client.GetAsync("api/customers/" + id).Result;
            if (resultado.IsSuccessStatusCode)
            {
                var destino = resultado.Content.ReadAsAsync<Customer>().Result;
                return View(destino);
            }
            else
            {
                return RedirectToAction("Index", new { mensajeNegativo = resultado.ReasonPhrase });
            }
        }

        [HttpPost]
        public ActionResult Delete(Customer customer)
        {
            var resultado = client.DeleteAsync("api/customers/" + customer.CustomerID).Result;
            if (resultado.IsSuccessStatusCode)
            {
                return RedirectToAction("Index", new { mensajePositivo = "Informacion guardada de manera exitosa" });
            }
            else
            {
                return RedirectToAction("Index", new { mensajeNegativo = resultado.ReasonPhrase });
            }
        }
    }
}

AirWaysClient/Views/Customers/Create.cshtml
@model AirWaysClient.Models.Customer

<h2>Clientes</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Nuevo Cliente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CustomerName, "Nombre", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerAdress, "Dirección", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerAdress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerAdress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerPhone, "Telefono", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerIDCard, "Numero Identificacion", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerIDCard, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerIDCard, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-danger" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    @if (ViewBag.mensajeNegativo != null)
    {
        <script type="text/javascript">
            $(document).ready(function () {
                swal("Error al guardar los datos", "@ViewBag.mensajeNegativo", "error");
            })
        </script>
    }
}

AirWaysClient/Views/Customers/Delete.cshtml
@model AirWaysClient.Models.Customer

<h2>Clientes</h2>
<div>
    <h4>Eliminar Cliente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.Label("Nombre")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerName)
        </dd>

        <dt>
            @Html.Label("Dirección")

        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerAdress)
        </dd>

        <dt>
            @Html.Label("Telefono")

        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerPhone)
        </dd>

        <dt>
            @Html.Label("Numero Identificación")

        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerIDCard)
        </dd>

    </dl>

    @using (Html.BeginForm("Delete","Customers",FormMethod.Post, new { @id= "FormDelete" }))
    {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(model => model.CustomerName)

        @Html.HiddenFor(model => model.CustomerAdress)

        @Html.HiddenFor(model => model.CustomerPhone)

        @Html.HiddenFor(model => model.CustomerIDCard)

        @Html.HiddenFor(model => model.CustomerID)
        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" id="delete" class="btn btn-default" /> |
            @Html.ActionLink("Volver", "Index",null, new { @class="btn btn-danger"})
        </div>
    }
</div>
@section scripts{
    <script type="text/javascript">
        $('#delete').click(function (e) {
            e.preventDefault();
            swal({
                title: "Eliminar Registro?",
                text: "El registro se eliminará de forma permanente",
                type: "warning",
                showCancelButton: true,
                confirmButtonClass: "btn-danger",
                confirmButtonText: "Borrar",
                cancelButtonText: "Cancelar",
                closeOnConfirm: false,
                closeOnCancel: false
            },
                function (isConfirm) {
                    if (isConfirm) {
                        $("#FormDelete").submit();
                    } else {
                        swal("Cancelado", "No de borrará el registro", "error");
                    }
                });

        })

    </script>
}

AirWaysClient/Views/Customers/Edit.cshtml
@model AirWaysClient.Models.Customer

<h2>Clientes</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Editar Cliente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CustomerID)

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerName,"Nombre", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerAdress, "Dirección", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerAdress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerAdress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerPhone, "Telefono", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerIDCard, "Numero Identificación", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerIDCard, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerIDCard, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index",null, new { @class="btn btn-danger"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AirWaysClient/Views/Customers/Index.cshtml
@model IEnumerable<AirWaysClient.Models.Customer>

<h2>Clientes</h2>

<p>
    @Html.ActionLink("Crear nuevo Cliente", "Create", null, new { @class = "btn btn-success" })
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.Label("Nombre")
            </th>
            <th>
                @Html.Label("Dirección")

            </th>
            <th>
                @Html.Label("Telefono")

            </th>
            <th>
                @Html.Label("Numero Identificación")
            </th>
            <th>
                @Html.Label("Acciones")
            </th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CustomerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CustomerAdress)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CustomerPhone)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CustomerIDCard)
                </td>
                <td>
                    @Html.ActionLink("Editar", "Edit", new { id = item.CustomerID }, new { @class="btn btn-info"}) 
                    @Html.ActionLink("Eliminar", "Delete", new { id = item.CustomerID }, new { @class = "btn btn-warning" })
                </td>
            </tr>
        }
    </tbody>

</table>

@section scripts{
    @if (ViewBag.mensajeNegativo != null)
    {
        <script type="text/javascript">
            $(document).ready(function () {
                swal("Error al leer los datos", "@ViewBag.mensajeNegativo", "error");
            })
        </script>
    }

    @if (ViewBag.mensajePositivo != null)
    {
        <script type="text/javascript">
            $(document).ready(function () {
                swal("Exito", "@ViewBag.mensajePositivo", "success");
            })
        </script>
    }
}